Website_tvsi_v1/Controllers/QhcodongController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TVSI.WebsiteDAL;
using PagedList;
using Website_tvsi_v1.Common;

namespace Website_tvsi_v1.Controllers
{
    public class QhcodongController : Controller
    {
        //
        // GET: /Qhcodong/
        public QhcodongController()
        {
            ViewBag.spdv_menu = "dropdown";
            ViewBag.hotro_menu = "dropdown";
            ViewBag.gttvsi_menu = "dropdown active";
            ViewBag.title = "Giao dịch và đầu tư cổ phiếu trực tuyến - Công Ty Cổ Phần Chứng Khoán Tân Việt (TVSI)-";
        }
        public ActionResult Baocaotaichinh(int page = 1, int pagesize = 8)
        {

            //int ngonngu_id = 1;
            int chuyen_muc_tvsiid = 58;
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            //66	Financial Statements
            if (ngonngu_id == 2)
            {
                chuyen_muc_tvsiid = 66;
            }
            DataTable data = new DataTable();
            data = TVSI_THONG_TIN_TVSI_v2.LayTheo_chuyen_muc_tin_tvsiid(ngonngu_id, chuyen_muc_tvsiid);
            List<DataRow> ds_bctaichinh = new List<DataRow>();
            foreach (DataRow dr in data.Rows)
            {
                ds_bctaichinh.Add(dr);
            }
            ViewBag.account = ds_bctaichinh.Count;
            var model = ds_bctaichinh.ToPagedList(page, pagesize);

            return View(model);
        }
        public ActionResult Thongtincongbo(int page = 1, int pagesize = 8)
        {
            int ngonngu_id = 1;
            int chuyen_muc_tvsiid = 59; //67	Published information
            DataTable data = new DataTable();
            data = TVSI_THONG_TIN_TVSI_v2.LayTheo_chuyen_muc_tin_tvsiid(ngonngu_id, chuyen_muc_tvsiid);
            List<DataRow> ds_ttcongbo = new List<DataRow>();
            foreach (DataRow dr in data.Rows)
            {
                ds_ttcongbo.Add(dr);
            }
            ViewBag.account = ds_ttcongbo.Count;
            var model = ds_ttcongbo.ToPagedList(page, pagesize);
            return View(model);

        }
        public ActionResult Baocaothuongnien(int page = 1, int pagesize = 6)
        {
           
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            int chuyen_muc_tvsiid = 62;//70	Annual Reports may test 72
            if (ngonngu_id == 2)
            {
                chuyen_muc_tvsiid = 70;
            }
           
            DataTable data = new DataTable();
            data = TVSI_THONG_TIN_TVSI_v2.LayTheo_chuyen_muc_tin_tvsiid(ngonngu_id, chuyen_muc_tvsiid);
            List<DataRow> ds_bcthuongnien = new List<DataRow>();
            foreach (DataRow dr in data.Rows)
            {
                ds_bcthuongnien.Add(dr);
            }
            ViewBag.account = ds_bcthuongnien.Count;
            var model = ds_bcthuongnien.ToPagedList(page, pagesize);
            return View(model);
        }
        public ActionResult Thongtincodong()
        {
            int id = 1140;
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            if (ngonngu_id == 2)
            {
                id = 1174;
            }
            ViewBag.thong_tin_selected = TVSI_THONG_TIN_TVSI_v2.ChiTiet_THONG_TIN_TVSI(ngonngu_id, id);
            return View();
        }
        public ActionResult Quantridoanhnghiep()
        {
            int id = 1141;
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            if (ngonngu_id == 2)
            {
                id = 1175;
            }
            ViewBag.thong_tin_selected = TVSI_THONG_TIN_TVSI_v2.ChiTiet_THONG_TIN_TVSI(ngonngu_id, id);
            return View();
        }
    }
}

Website_tvsi_v1/Views/Qhcodong/Baocaotaichinh.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var count = ViewBag.account;
}
@model PagedList.IPagedList<System.Data.DataRow>
@using PagedList.Mvc;
<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/upload/gioithieu_hoatDongTvsi_banner.jpg" alt="" class="background-banner">

        @*<div class="container">
            <h1 class="title-page">@Website_tvsi_v1.App_Resources.Website.Text_FinanceReport</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Html.Raw(Website_tvsi_v1.App_Resources.Website.Txt_ShareholderrelationsF)
                    </div>
                    <div class="wrapper">
                        <ul class="list-unstyled">
                            <li class="active"><a href="/introduction/report-finance"><i class="fa fa-caret-right"></i>@Website_tvsi_v1.App_Resources.Website.Text_FinanceReport</a></li>
                            <li><a href="/introduction/information-publish"><i class="fa fa-caret-right"></i>@Website_tvsi_v1.App_Resources.Website.Txt_Publishedinfor</a></li>
                            <li><a href="/introduction/admin-business"><i class="fa fa-caret-right"></i>@Website_tvsi_v1.App_Resources.Website.Txt_CorporateGovernance</a></li>
                            <li><a href="/introduction/information-shareholder"><i class="fa fa-caret-right"></i>@Website_tvsi_v1.App_Resources.Website.Txt_Shareholderinfor</a></li>
                            <li><a href="/introduction/report-annual"><i class="fa fa-caret-right"></i>@Website_tvsi_v1.App_Resources.Website.Text_AnnualReport</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                <div class="table-responsive">
                    <table class="table table-default col2">
                        <thead>
                            <tr>
                                <th>@Website_tvsi_v1.App_Resources.Website.Txt_Document</th>
                                <th>@Website_tvsi_v1.App_Resources.Website.Txt_Update</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><a target="_blank" href="@item["noi_dung"]">@item["tieu_de"]</a></td>
                                    <td>@Website_tvsi_v1.Common.CommonFnc.FormatDate(item["ngay_dang_tai"].ToString())</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                @if(count > 8)
                {
                    <div class="pager">
                        <ul class="list-unstyled">
                            <li>@Html.PagedListPager(Model, page => Url.Action("baocaotaichinh", "Qhcodong", new { page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)</li>
                        </ul>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Qhcodong/Baocaothuongnien.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var count = ViewBag.account;
}
@model PagedList.IPagedList<System.Data.DataRow>
@using PagedList.Mvc;
<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/upload/gioithieu_QuanHeCoDong_BaoCaoThuongNien_banner.png" alt="" class="background-banner">

        @*<div class="container">
            <h1 class="title-page dark">@Website_tvsi_v1.App_Resources.Website.Text_AnnualReport</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Html.Raw(Website_tvsi_v1.App_Resources.Website.Txt_ShareholderrelationsF)
                    </div>
                    <div class="wrapper">
                        <ul class="list-unstyled">
                            <li><a href="/introduction/report-finance"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Text_FinanceReport</a></li>
                            <li><a href="/introduction/information-publish"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_Publishedinfor</a></li>
                            <li><a href="/introduction/admin-business"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_CorporateGovernance</a></li>
                            <li><a href="/introduction/information-shareholder"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_Shareholderinfor</a></li>
                            <li class="active"><a href="/introduction/report-annual"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Text_AnnualReport</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                <div class="detail-content has-title-part">
                    <div class="part">
                        <!--<h3 class="title">Báo cáo thường niên</h3>-->

                        <div class="wrapper">
                            <div class="list-media annual-reports">
                                @foreach(var item in Model){
                                    <div class="item text-center">
                                    <div class="thumb">
                                        <a target="_blank" href="@item["noi_dung"]" title="">
                                            <img src="/images/baocaothuongnien/@item["duong_dan_file_anh"]" alt="..">
                                        </a>
                                    </div>
                                    <div class="wrapper">
                                        <a target="_blank" href="@item["noi_dung"]" title="">@item["tieu_de"]
                                        </a>
                                    </div>
                                </div>
                                }
                            </div>
                            @if(count>6){
                              <div class="pager">
                                <ul class="list-unstyled">
                                  <li>@Html.PagedListPager(Model, page => Url.Action("baocaothuongnien","Qhcodong", new {page}),PagedListRenderOptions.OnlyShowFivePagesAtATime)</li>
                                </ul>
                              </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Qhcodong/Quantridoanhnghiep.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var thong_tin_selected = (System.Data.DataTable)ViewBag.thong_tin_selected;
}

<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/upload/gioithieu_QuanHeCoDong_QuanTriDoanhNghiep_banner.png" alt="" class="background-banner">

        @*<div class="container">
            <h1 class="title-page">@Website_tvsi_v1.App_Resources.Website.Txt_CorporateGovernance</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Html.Raw(Website_tvsi_v1.App_Resources.Website.Txt_ShareholderrelationsF)
                    </div>
                    <div class="wrapper">
                        <ul class="list-unstyled">
                            <li><a href="/introduction/report-finance"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Text_FinanceReport</a></li>
                            <li><a href="/introduction/information-publish"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_Publishedinfor</a></li>
                            <li class="active"><a href="/introduction/admin-business"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_CorporateGovernance</a></li>
                            <li><a href="/introduction/information-shareholder"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_Shareholderinfor</a></li>
                            <li ><a href="/introduction/report-annual"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Text_AnnualReport</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                @Html.Raw(thong_tin_selected.Rows[0]["noi_dung"].ToString())
                 <script>
                     $(".panel-title a").attr("data-toggle", "collapse");
                     $(".panel-title a").attr("data-parent", "#accordion");
                </script>
           </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Qhcodong/Thongtincodong.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var thong_tin_selected = (System.Data.DataTable)ViewBag.thong_tin_selected;
}

<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/upload/gioithieu_QuanHeCoDong_ThongTinCoDong_banner.png" alt="" class="background-banner">

        @*<div class="container">
            <h1 class="title-page dark">@Website_tvsi_v1.App_Resources.Website.Txt_Shareholderinfor</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Html.Raw(Website_tvsi_v1.App_Resources.Website.Txt_ShareholderrelationsF)
                    </div>
                    <div class="wrapper">
                        <ul class="list-unstyled">
                            <li><a href="/introduction/report-finance"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Text_FinanceReport</a></li>
                            <li><a href="/introduction/information-publish"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_Publishedinfor</a></li>
                            <li><a href="/introduction/admin-business"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_CorporateGovernance</a></li>
                            <li class="active"><a href="/introduction/information-shareholder"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_Shareholderinfor</a></li>
                            <li ><a href="/introduction/report-annual"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Text_AnnualReport</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                @Html.Raw(thong_tin_selected.Rows[0]["noi_dung"].ToString())
                 <script>
                     $(".panel-title a").attr("data-toggle", "collapse");
                     $(".panel-title a").attr("data-parent", "#accordion");
                </script>
           </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Qhcodong/Thongtincongbo.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var count = ViewBag.account;
}
@model PagedList.IPagedList<System.Data.DataRow>
@using PagedList.Mvc;
<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/upload/gioithieu_QuanHeCoDong_ThongTinCongBo_banner.png" alt="" class="background-banner">

        @*<div class="container">
            <h1 class="title-page">@Website_tvsi_v1.App_Resources.Website.Txt_Publishedinfor</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Html.Raw(Website_tvsi_v1.App_Resources.Website.Txt_ShareholderrelationsF)
                    </div>
                    <div class="wrapper">
                        <ul class="list-unstyled">
                            <li><a href="/introduction/report-finance"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Text_FinanceReport</a></li>
                            <li class="active"><a href="/introduction/information-publish"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_Publishedinfor</a></li>
                            <li><a href="/introduction/admin-business"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_CorporateGovernance</a></li>
                            <li><a href="/introduction/information-shareholder"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Txt_Shareholderinfor</a></li>
                            <li><a href="/introduction/report-annual"><i class="fa fa-caret-right"></i> @Website_tvsi_v1.App_Resources.Website.Text_AnnualReport</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                <div class="table-responsive">
                    <table class="table table-default col2">
                        <thead>
                        <tr>
                            <th>@Website_tvsi_v1.App_Resources.Website.Txt_Document</th>
                            <th>@Website_tvsi_v1.App_Resources.Website.Txt_Update</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                            <td><a target="_blank" href="@item["noi_dung"]">@item["tieu_de"]</a></td>
                            <td>@Website_tvsi_v1.Common.CommonFnc.FormatDate(item["ngay_dang_tai"].ToString())</td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
               @if(count>8)
               {
                <div class="pager">
                    <ul class="list-unstyled">
                      <li>@Html.PagedListPager(Model, page => Url.Action("thongtincongbo","Qhcodong", new {page}),PagedListRenderOptions.OnlyShowFivePagesAtATime)</li>
                    </ul>
               </div>
               }
            </div>
        </div>
    </div>
</section>