Website_tvsi_v1/Controllers/HotroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using TVSI.WebsiteDAL;
using Website_tvsi_v1.App_Data;
using Website_tvsi_v1.EFAQWS;
using Website_tvsi_v1.Models;
using PagedList;
using System.Data;
using Website_tvsi_v1.Common;

namespace Website_tvsi_v1.Controllers
{
    public class HotroController : Controller
    {
        //
        // GET: /Hotro/
        private string name_service = "customer support";

        public HotroController()
        {
            ViewBag.spdv_menu = "dropdown";
            ViewBag.hotro_menu = "dropdown active";
            ViewBag.gttvsi_menu = "dropdown";
            ViewBag.title = "Công Ty Cổ Phần Chứng Khoán Tân Việt (TVSI)- Thông tin hỗ trợ!";
        }

        public ActionResult Index()
        {
            return View();
        }

        // lay danh sach thong tin cua chuyen muc ho tro
       //chuyen muc ho tro id=7
        public void danhmucmennuhotro()
        {
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]); 
            //id danh muc cha ho tro
            int danh_muc_phu_thuocid = 7;
            if (ngonngu_id == 2)
            {
                danh_muc_phu_thuocid = 17;
            }
            var menu_hotro = TVSI_DANH_MUC_HO_TRO_v3.Laytheo_danh_muc_phu_thuocid(ngonngu_id, danh_muc_phu_thuocid);
            // menu ho tro tvsi 
            int danhmuc_id1 = int.Parse(menu_hotro.Rows[0]["danh_muc_ho_troid"].ToString());
            ViewBag.huong_dan_giao_dich = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
            danhmuc_id1 = int.Parse(menu_hotro.Rows[1]["danh_muc_ho_troid"].ToString());
            ViewBag.huong_dan_giao_dich_tien = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
            danhmuc_id1 = int.Parse(menu_hotro.Rows[2]["danh_muc_ho_troid"].ToString());
            ViewBag.huong_dan_tra_cuu = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
            danhmuc_id1 = int.Parse(menu_hotro.Rows[3]["danh_muc_ho_troid"].ToString());
            ViewBag.cac_bieu_mau = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
            danhmuc_id1 = int.Parse(menu_hotro.Rows[4]["danh_muc_ho_troid"].ToString());
            ViewBag.kien_thuc_va_hoi_dap = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
        }
        //dieu huong cua menu huong dan giao dich co phieu
        public PartialViewResult NavigationHDgiaodich()
        {

            danhmucmennuhotro();
            return PartialView();
        }
        //dieu huong cua menu huong dan giao dich tien
        public PartialViewResult navigationHDgiaodichtien()
        {
            danhmucmennuhotro();
            return PartialView();
        }
        //dieu huong cua menu huong dan chuyen tien
        public PartialViewResult NavigationHDchuyentien()
        {
            danhmucmennuhotro();
            return PartialView();
        }
        //dieu huong cua menu huong dan tra cuu va quan ly tai san
        public PartialViewResult NavigationHDtracuu()
        {
            danhmucmennuhotro();
            return PartialView();
        }
        public PartialViewResult NavigationHoidap()
        {
            danhmucmennuhotro();
            return PartialView();
        }
        public PartialViewResult NavigationKienthuc()
        {
            danhmucmennuhotro();
            return PartialView();
        }
        public PartialViewResult NavigationKinhnghiem()
        {
            danhmucmennuhotro();
            return PartialView();

        }
        public PartialViewResult NavigationBieumau()
        {
            danhmucmennuhotro();
            return PartialView();
        }


        // trang chi tiet cua menu ho tro
        public ActionResult HuongdanTvsi(int id = 18)
        {
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            var tvsi_map_thong_tin = TVSI_THONG_TIN_TVSI_v2.LayTheo_tvsi_map_ngon_ngu_id(id, name_service);
            if (ngonngu_id == 1)
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_viet_nam"].ToString());
            }
            else
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_english"].ToString());
            }
            var thong_tin_ho_tro_selected = TVSI_THONG_TIN_HO_TRO_v2.LayTheo_thong_tin_ho_tro_id_2017(id);
            ViewBag.thong_tin_ho_tro_selected = thong_tin_ho_tro_selected;
            int danhmuc_cha_id = 7;
            if (ngonngu_id == 2)
            {
                danhmuc_cha_id = 17;
            }
            var menu_hotro = TVSI_DANH_MUC_HO_TRO_v3.Laytheo_danh_muc_phu_thuocid(ngonngu_id, danhmuc_cha_id);
            // menu khach hang doanh nghiep
            int danhmuc_id1 = int.Parse(menu_hotro.Rows[0]["danh_muc_ho_troid"].ToString());
            ViewBag.huong_dan_giao_dich = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
            danhmuc_id1 = int.Parse(menu_hotro.Rows[1]["danh_muc_ho_troid"].ToString());
            ViewBag.huong_dan_giao_dich_tien = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
            danhmuc_id1 = int.Parse(menu_hotro.Rows[2]["danh_muc_ho_troid"].ToString());
            ViewBag.huong_dan_tra_cuu = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
            danhmuc_id1 = int.Parse(menu_hotro.Rows[3]["danh_muc_ho_troid"].ToString());
            ViewBag.cac_bieu_mau = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
            danhmuc_id1 = int.Parse(menu_hotro.Rows[4]["danh_muc_ho_troid"].ToString());
            ViewBag.kien_thuc_va_hoi_dap = TVSI_THONG_TIN_HOTRO_v3.LayTheo_danh_muc_ho_troid(ngonngu_id, danhmuc_id1);
            return View();
        }
        // chuyen muc hd_giao dich co phieu id=9
        public ActionResult HDgiaodichcophieu(int id=21)
        {
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            var tvsi_map_thong_tin = TVSI_THONG_TIN_TVSI_v2.LayTheo_tvsi_map_ngon_ngu_id(id, name_service);
            if (ngonngu_id == 1)
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_viet_nam"].ToString());
            }
            else
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_english"].ToString());
            }
            ViewBag.thong_tin_ho_tro = TVSI_THONG_TIN_HO_TRO_v2.LayTheo_thong_tin_ho_tro_id_2017(id);
            return View();
        }
        //chuyen muc hd_nop tien chuyen muc id=11
        public ActionResult HDnoptien(int id = 28)
        {
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            var tvsi_map_thong_tin = TVSI_THONG_TIN_TVSI_v2.LayTheo_tvsi_map_ngon_ngu_id(id, name_service);
            if (ngonngu_id == 1)
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_viet_nam"].ToString());
            }
            else
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_english"].ToString());
            }
            ViewBag.thong_tin_ho_tro = TVSI_THONG_TIN_HO_TRO_v2.LayTheo_thong_tin_ho_tro_id_2017(id);
            return View();
        }
        // trang cua menu huong dan chuyen tien khong dung
        public ActionResult HDchuyentien(int id = 100)
        {
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            var tvsi_map_thong_tin = TVSI_THONG_TIN_TVSI_v2.LayTheo_tvsi_map_ngon_ngu_id(id, name_service);
            if (ngonngu_id == 1)
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_viet_nam"].ToString());
            }
            else
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_english"].ToString());
            }
            ViewBag.thong_tin_ho_tro = TVSI_THONG_TIN_HO_TRO_v2.LayTheo_thong_tin_ho_tro_id_2017(id);
            return View();
        }
        // chuyen muc hd_tra cuu id =13
        public ActionResult HDtracuu(int id = 33)
        {
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            var tvsi_map_thong_tin = TVSI_THONG_TIN_TVSI_v2.LayTheo_tvsi_map_ngon_ngu_id(id, name_service);
            if (ngonngu_id == 1)
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_viet_nam"].ToString());
            }
            else
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_english"].ToString());
            }
            ViewBag.thong_tin_ho_tro = TVSI_THONG_TIN_HO_TRO_v2.LayTheo_thong_tin_ho_tro_id_2017(id);
            return View();
        }
        // chuyen muc hotro_cac bieu mau id=15
        public ActionResult Cacbieumau(int id = 37)
        {
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);
            var tvsi_map_thong_tin = TVSI_THONG_TIN_TVSI_v2.LayTheo_tvsi_map_ngon_ngu_id(id, name_service);
            if (ngonngu_id == 1)
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_viet_nam"].ToString());
            }
            else
            {
                id = int.Parse(tvsi_map_thong_tin.Rows[0]["id_english"].ToString());
            }
            ViewBag.thong_tin_ho_tro = TVSI_THONG_TIN_HO_TRO_v2.LayTheo_thong_tin_ho_tro_id_2017(id);
            return View();
        }
        // tim kiem hoi dap FAQ theo webservice
        public ActionResult HoidapFAQ(String search, int page = 1, int pagesize = 5)
        {
            int ngonngu_id = CommonFnc.getLanguage(Request.Cookies[CommonConstant.name_lang_tvsi_wb]);

            int id = 62;

Website_tvsi_v1/Views/Hotro/Cacbieumau.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var thong_tin_ho_tro = (System.Data.DataTable)ViewBag.thong_tin_ho_tro;
}
<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/upload/hotro_HDGiaoDich_HDMoTK_banner.png" alt="" class="background-banner">

        @*<div class="container">
            <h1 class="title-page dark">@thong_tin_ho_tro.Rows[0]["tieu_de"]</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top desktop">
                <div class="sidebar-box">
                    <div class="title">
                        @Website_tvsi_v1.App_Resources.Website.Txt_CustomerServices
                    </div>
                    @{Html.RenderAction("NavigationBieumau", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                @Html.Raw(thong_tin_ho_tro.Rows[0]["noi_dung"].ToString())
                <script>
                    $(".panel-title a").attr("data-toggle", "collapse");
                    $(".panel-title a").attr("data-parent", "#accordion");
                </script>
              <div class="sidebar di-table-cell vertical-top mobile">
                <div class="sidebar-box">
                    <div class="title">
                        Hỗ trợ
                    </div>
                    @{Html.RenderAction("NavigationBieumau", "hotro");}
                </div>
            </div>
           </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Hotro/ChitietKinhnghiem.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var chi_tiet_kinh_nghiem = (System.Data.DataTable)ViewBag.chi_tiet_kinh_nghiem;
    var beta = "";
}

<section id="wrapper-top-content">
    <div class="banner">
        <img src="@beta/images/upload/HoTro_KienThucHoiDap_banner.png" alt="" class="background-banner">

        @*<div class="container">
            <h1 class="title-page gray">@Website_tvsi_v1.App_Resources.Website.Txt_Sharing</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top desktop">
                <div class="sidebar-box">
                    <div class="title">
                        @Website_tvsi_v1.App_Resources.Website.Txt_CustomerServices
                    </div>
                    @{Html.RenderAction("NavigationKinhnghiem", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top" style="font-size:18px">
                <p><strong>@chi_tiet_kinh_nghiem.Rows[0]["tieu_de"]</strong></p>
                @Html.Raw(chi_tiet_kinh_nghiem.Rows[0]["noi_dung"].ToString())
            
               <div class="sidebar di-table-cell vertical-top mobile">
                <div class="sidebar-box">
                    <div class="title">
                        Hỗ trợ
                    </div>
                    @{Html.RenderAction("NavigationKinhnghiem", "hotro");}
                </div>
            </div>
            </div>
        </div>
    </div>
 </section>

Website_tvsi_v1/Views/Hotro/HDchuyentien.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var thong_tin_ho_tro = (System.Data.DataTable)ViewBag.thong_tin_ho_tro;
}
<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/upload/hotro_HDGiaoDich_HDMoTK_banner.png" alt="" class="background-banner">

        @*<div class="container">
            <h1 class="title-page dark">@thong_tin_ho_tro.Rows[0]["tieu_de"]</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Website_tvsi_v1.App_Resources.Website.Txt_CustomerServices
                    </div>
                    @{Html.RenderAction("NavigationHDchuyentien", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                <p>
                    @Html.Raw(thong_tin_ho_tro.Rows[0]["noi_dung"].ToString())
                </p>
                <script>
                    $(".panel-title a").attr("data-toggle", "collapse");
                    $(".panel-title a").attr("data-parent", "#accordion");
                </script>
           </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Hotro/HDchuyentienonline.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
}

<section id="wrapper-top-content">
    <div class="banner">
        <img src="/beta/images/upload/hotro_HDGiaoDich_HDMoTK_banner.png" alt="" class="background-banner">

        <div class="container">
            <h1 class="title-page dark">Hướng dẫn giao dịch tiền</h1>
        </div>
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        Hỗ trợ
                    </div>
                    @{Html.RenderAction("NavigationHDchuyentien", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                Nội dung hướng dẫn chuyển tiền Online
            </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Hotro/HDgiaodichcophieu.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var thong_tin_ho_tro = (System.Data.DataTable)ViewBag.thong_tin_ho_tro;
}
<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/banner/Huongdangiaodich.png" alt="" class="background-banner">
        @*<div class="container">
            <h1 class="title-page">@thong_tin_ho_tro.Rows[0]["tieu_de"]</h1>
        </div>*@    
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Website_tvsi_v1.App_Resources.Website.Txt_CustomerServices
                    </div>
                    @{Html.RenderAction("NavigationHDgiaodich", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                @Html.Raw(thong_tin_ho_tro.Rows[0]["noi_dung"].ToString())
                <script>
                    $(".panel-title a").attr("data-toggle", "collapse");
                    $(".panel-title a").attr("data-parent", "#accordion");
                </script>
           </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Hotro/HDnoptien.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var thong_tin_ho_tro = (System.Data.DataTable)ViewBag.thong_tin_ho_tro;
}
<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/banner/Huongdangiaodichtien.png" alt="" class="background-banner">
        @*<div class="container">
            <h1 class="title-page">@thong_tin_ho_tro.Rows[0]["tieu_de"]</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Website_tvsi_v1.App_Resources.Website.Txt_CustomerServices
                    </div>
                    @{Html.RenderAction("navigationHDgiaodichtien", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                @Html.Raw(thong_tin_ho_tro.Rows[0]["noi_dung"].ToString())
                <script>
                    $(".panel-title a").attr("data-toggle", "collapse");
                    $(".panel-title a").attr("data-parent", "#accordion");
                </script>
           </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Hotro/HDnoptienkhac.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
}

<section id="wrapper-top-content">
    <div class="banner">
        <img src="/beta/images/upload/hotro_HDGiaoDich_HDMoTK_banner.png" alt="" class="background-banner">

        <div class="container">
            <h1 class="title-page dark">Hướng dẫn giao dịch tiền</h1>
        </div>
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        Hỗ trợ
                    </div>
                    @{Html.RenderAction("NavigationHDgiaodichtien", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                Nội dung hướng dẫn nộp tiền khác
            </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Hotro/HDnoptientaiquay.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
}

<section id="wrapper-top-content">
    <div class="banner">
        <img src="/beta/images/upload/hotro_HDGiaoDich_HDMoTK_banner.png" alt="" class="background-banner">

        <div class="container">
            <h1 class="title-page dark">Hướng dẫn giao dịch tiền</h1>
        </div>
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        Hỗ trợ
                    </div>
                    @{Html.RenderAction("NavigationHDgiaodichtien", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                Nội dung hướng dẫn nộp tiền tại quầy
            </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Hotro/HDtracutaikhoankyquy.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
}

<section id="wrapper-top-content">
    <div class="banner">
        <img src="/beta/images/upload/hotro_HDGiaoDich_HDMoTK_banner.png" alt="" class="background-banner">

        <div class="container">
            <h1 class="title-page dark">Hướng dẫn tra cứu và quản lý tài sản</h1>
        </div>
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        Hỗ trợ
                    </div>
                    @{Html.RenderAction("NavigationHDtracuu", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                Nội dung hướng dẫn tra cứu tài khoản ký quý
            </div>
        </div>
    </div>
</section>

Website_tvsi_v1/Views/Hotro/HDtracuu.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    var thong_tin_ho_tro = (System.Data.DataTable)ViewBag.thong_tin_ho_tro;
}
<section id="wrapper-top-content">
    <div class="banner">
        <img src="/images/banner/Huongdantracuuvaquanlytaisan.png" alt="" class="background-banner">
        @*<div class="container">
            <h1 class="title-page dark">@thong_tin_ho_tro.Rows[0]["tieu_de"]</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Website_tvsi_v1.App_Resources.Website.Txt_CustomerServices
                    </div>
                    @{Html.RenderAction("NavigationHDtracuu", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                @Html.Raw(thong_tin_ho_tro.Rows[0]["noi_dung"].ToString())
                <script>
                    $(".panel-title a").attr("data-toggle", "collapse");
                    $(".panel-title a").attr("data-parent", "#accordion");
                </script>
            </div>
           </div>
        </div>
</section>

Website_tvsi_v1/Views/Hotro/HoidapKienthuc.cshtml
@{
    Layout = "~/Views/Home/Share/_Layout.cshtml";
    int total_record = ViewBag.total_record;
    var beta = "";
}
@model PagedList.IPagedList<System.Data.DataRow>
@using PagedList.Mvc;
<section id="wrapper-top-content">
    <div class="banner">
        <img src="@beta/images/upload/hotro_KienThucHoiDap_banner.png" alt="" class="background-banner">

        @*<div class="container">
            <h1 class="title-page gray">@Website_tvsi_v1.App_Resources.Website.Txt_knowledge</h1>
        </div>*@
    </div>
</section>
<section id="wrapper-content" class="inner-page">
    <div class="container">
        <div class="row di-table">
            <div class="sidebar di-table-cell vertical-top">
                <div class="sidebar-box">
                    <div class="title">
                        @Website_tvsi_v1.App_Resources.Website.Txt_CustomerServices
                    </div>
                    @{Html.RenderAction("NavigationKienthuc", "hotro");}
                </div>
            </div>
            <div class="main-content di-table-cell vertical-top">
                <div class="detail-content has-title-part">
                    <div class="part">
                        <h3 class="title di-table">
                            <span class="di-table-cell">@Website_tvsi_v1.App_Resources.Website.Txt_knowledge</span>
                            <div class="search-keyword di-table-cell">
                                <div class="search-box ">
                                    @using (Html.BeginForm("HoidapKienthuc", "Hotro", FormMethod.Get))
                                            {
                                                <input type="text" class="search-input" name="search" value="@ViewBag.search" placeholder="@Website_tvsi_v1.App_Resources.Website.Txt_Keywordrequired">
                                                                                                                        <button type="submit" class="search-button"><i class="fa fa-search"></i></button>
                                            }
                                </div>
                            </div>
                        </h3>

                        @if(Model!=null){
                            <div class="wrapper">
                            <ul class="simple-list" id="knowledge">
                                @foreach( var item in Model)
                                {
                                <li>
                                    <a href="@beta/customer-support/detail-answer-knowledge/@item["thong_tin_kien_thucid"]">@item["tieu_de"]</a>
                                </li>
                                }
                            </ul>
                            <div class="pager">
                                <ul class="list-unstyled">
                                    @if(total_record>10)
                                    {
                                        <li>@Html.PagedListPager(Model, page => Url.Action("HoidapKienthuc","Hotro", new {page, @search=@ViewBag.search}),PagedListRenderOptions.OnlyShowFivePagesAtATime)</li>
                                    }
                                </ul>
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>
            </div>
        </div>
</section>